export class Product {
    id: number;
    name: string;
    date: string;
    desc: any;
    img: string;
    price: number;
}

export const PRODUCTS: Product[] = [
    { id: 1, name: 'Pharrell x adidas NMD Hu "Holi Festival"', date: 'March, 2018', img: '1.jpg', price: 220, desc: 'Pharrell\u2019s upcoming \u201CHoli Festival\u201D collaboration with adidas has garnered a lot of attention, as it is spanning across three different silhouettes. Most notably of course, the aesthetic will be adorning the NMD Hu silhouette in multiple colorways including this clean black version.  In celebration of one of India\u2019s most important festivals, most of the honorary selections comes with wild paint-like color schemes, which makes this black pair all the more intriguing. Initially, they were scheduled to release on March 2nd, but has since been pushed pack to a later date next month. Enjoy a complete set of official images below and stay up-to-date on release details as they become available.' },
    { id: 2, name: 'adidas NMD CS2', date: 'March, 2018', img: '2.jpg', price: 180, desc: 'adidas\u2019 NMD CS2 silhouette is back in the always popular \u201CTriple Black\u201D colorway with hits of Solar Red on its ankle collar. Featuring a full black Primeknit upper, it is dressed with subtle tonal camouflage patterns mixed in, while sitting a top the often-preferred black BOOST midsole. While adidas\u2019 NMD line has been losing its energy as of late, this incredibly popular aesthetic could help one of the brand\u2019s most important shoes regain a bit of its flare. No specific release information is currently available, but expect the newest NMD to arrive at adidas stockists in March with a price tag of $180 USD.' },
    { id: 3, name: 'Neighborhood x adidas NMD R1 PK', date: 'February 24, 2018', img: '3.jpg', price: 220, desc: 'Re-igniting their collaborative relationship, adidas and the Japanese streetwear label NEIGHBORHOOD are preparing to launch a four-piece collection. NBHD founder Shinsuke Takazawa brings his unparalleled monochrome aesthetic on all four pieces, as they are all dressed up in black and white. Starting with the NMD R1 PK, the capsule is inspired by the label\u2019s roots in motorcycle culture, as each selection portrays a rough and rugged look. Completing this premium collection, is the  I-5923, the Gazelle Super, and the Chop Shop silhouette, which is a brand new adidas model that has been made specifically for this collaboration. It combines a vintage-inspired upper with a modernized BOOST midsole that paints Takazawa\u2019s aesthetic in a brand new light. Fans of this simplistic, yet sophisticated capsule will also have a full-scale apparel collection that includes items ranging from jerseys to track jackets. Grab some official images of all four footwear pieces below, and mark your calendars for a global November 24th release.' },
    { id: 4, name: 'Pharrell x adidas NMD Hu Trail', date: 'March 2nd, 2018', img: '4.jpg', price: null, desc: 'Four colorways of the Pharrell x adidas NMD Hu Trail are scheduled for a release on March 2nd \u2013 one of them being this color-bombed rendition said to be inspired by India\u2019s Holi Festival that takes placed in early March. This color takes on softer shades compared to the other Holi-inspired NMD Hu shoes and also features marbled detailing on the bumpers on the midsole. The larger conversation is how Pharrell has been front and center for adidas over the last eighteen months, putting out impressive and inspirational footwear and apparel while making appearances at key brand events, while Kanye\u2019s YEEZY camp continues its independent operation. See below for a look at the official images of the upcoming Pharrell x adidas NMD Hu Trail and brush up on the other three that are dropping on March 2nd here.' },
    { id: 5, name: 'adidas NMD Hu “China Exclusive”', date: 'May 2018', img: '5.jpg', price: null, desc: 'adidas Originals is set to release four adidas NMD Human Race colorways exclusively in China this May. According to Yeezy Mafia, this collection features the words \u201CHappy\u201D, \u201CPassion\u201D, \u201CPeace\u201D, and \u201CYouth\u201D embroidered onto the uppers of the shoes in four corresponding color themes in either a camo-style Primeknit pattern or a water-color style aesthetic. This set closely resembles the first set of Pharrell\u2019s adidas NMD Hu drops from 2016, and given its limited release in China, these will likely fetch high dollars on the secondary market. Get a closer look here and be sure to check out what Billionaire Boys Club has in store for October.'},
    { id: 6, name: 'BBC x adidas NMD Hu', date: 'October 2018', img: '6.jpg', price: null, desc: 'In early January it was confirmed that Billionaire Boys Club was releasing another exclusive adidas NMD Hu collaboration for Fall 2018. Yeezy Mafia just revealed what\u2019s to come from the BBC x adidas partnership in 2018 \u2013 an NMD Hu Trail \u201CHeart/Mind\u201D that features bold stripes on the upper with a white, navy, red, and yellow colorway. Expected to release in October in very limited quantity, this design by BBC may or may not be what was previously confirmed, meaning 2018 will see a lot more from BBC and adidas. Stay tuned for more updates on the adidas NMD Hu front and let us know if these are better than last year\u2019s \u201Ccotton candy\u201D colorway.' },
    { id: 7, name: 'Neighborhood x adidas NMD', date: 'February 25, 2018', img: '7.jpg', price: 200, desc: 'While Neighborhood\u2019s adidas NMD collaboration was first previewed last year, it is finally back in the news with an official set of images. Following a similar aesthetic to the Japanese boutique\u2019s 2015 ZX 500 collaboration, white shark teeth are present, serving as a major focal point of the sneaker. adidas chooses to switch out it customary Three Stripes branding on its heel tab with a new look \u201CNBHD\u201D styling. Following up the three-entity collaboration between Neighborhood x Invincible x adidas NMD, this effort keeps this silhouette near the top of the collaborative pedestal. Fans of this unique look will be able to pick up a pair when they become available on February 24th for $200 USD.' },
    { id: 8, name: 'adidas NMD Racer', date: 'February 2, 2018', img: '8.jpg', price: null, desc: 'Following its JUICE HK collaboration, the adidas NMD Racer is back once again with two colorways that are fittingly bold to match its new boisterous tooling. First, is a Vivid Pink colorway that uses black details and a matching outsole for contrast, finished off with some colorful hits on its arch stabilizers. Alongside it is the Ash Grey variety that assumes a bit of a more understated color scheme featuring blue and orange accents. Once again, the Three Stripes masterfully blends classic design concepts with contemporary stylings for its newest NMD model. Mark your calendars for February 2nd when both of these new NMD Racer colorways will be available at adidas stockists worldwide.' },
    { id: 9, name: 'JUICE HK x adidas NMD Racer', date: 'January 20th, 2018 (Global)', img: '9.jpg', price: null, desc: 'Last week, JUICE HK\u2019s adidas NMD Racer collaboration made its debut exclusivey at the Hong Kong-based retailer. Tomorrow, the first Racer collaborative effort will be unveiled to the world as it arrives at Consortium accounts all around the globe. CLOT\u2019s Alienegra motif takes center stage as its unapologetic aesthetic encompasses the Core Black Primeknit upper and makes its way all the way down to thew marbled outsole. Form truly does meet function with the new NMD Racer, as its updated tooling creates extra support while also providing designers with new elements to dress up. The JUICE HK x adidas NMD Racer will be available at select Consortium Accounts on January 20th with an MSRP of \u20AC220.00. Will you be trying to snag a pair tomorrow?' },
    { id: 10, name: 'adidas NMD Racer', date: 'February 1, 2018', img: '10.jpg', price: null, desc: 'adidas\u2019s newest NMD silhouette recently made its world debut, sporting a new-look construction with updated midfoot bumpers that are utilized on the sneaker\u2019s arch for utility and also add another color blocking elements. A new racing style traction pattern also makes its way onto the outsole of the NMD Racer and extends fully toward the toe for increased durability and even more added functionality. Adorned in Solar Pink, this offering utilizes a primeknit construction with touches of black mixed into the pattern that matches the outsole, heel bumper, and Three-Stripes heel tab. While adidas\u2019s NMD line has lost a bit of its luster since its inception, the new look of the Racer is an attempt to stir the pot and get things going again. Do you think this is a step in the right direction for the Trefoil Brand? Head over to your local adidas retailer and grab a pair of these Solar Pink NMD Racers on February 1st.' },

];



